export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const SWITCH_EDIT = "SWITCH_EDIT";
export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED";
export const CLEAR_EDIT_MESSAGE = "CLEAR_EDIT_MESSAGE";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

export const USER_TASK_REQUEST = "USER_TASK_REQUEST";
export const USER_TASKS_RECEIVED = "USER_TASKS_RECEIVED";
export const USER_TASK_FAILED = "REQUEST_TASK_FAILED";

export const SET_ACTIVE_TASK = "SET_ACTIVE_TASK";

export const CHANGE_TASK_STATUS_REQ = "CHANGE_TASK_STATUS_REQ";
export const UPDATE_ACTIVE_TASK = "UPDATE_ACTIVE_TASK";
export const CHANGE_TASK_STATUS_FAIL = "CHANGE_TASK_STATUS_FAIL";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILED = "ADD_TASK_FAILED";
export const CLEAR_ADD_TASK_MESSAGE = "CLEAR_ADD_TASK_MESSAGE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED";

export const CLEAR_COMMENT_SERVER_MESSAGE = "CLEAR_COMMENT_SERVER_MESSAGE";

export const BOARD_DATA_REQUEST = "BOARD_DATA_REQUEST";
export const BOARD_DATA_SUCCESS = "BOARD_DATA_SUCCESS";
export const BOARD_DATA_FAILED = "BOARD_DATA_FAILED";
export const GET_ALL_TASKS = "GET_ALL_TASKS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
